config/routes.rb
Rails.application.routes.draw do
  root 'surveys#home'
  get 'survey' => 'surveys#new'
  get 'api' => 'surveys#api'

  resources :surveys

end

app/models/survey.rb
class Survey < ActiveRecord::Base

  validates :name, presence: true, length: { maximum: 50 }
  validates :age, presence: true
  validates :gender, presence: true, length: { maximum: 20 }
  # validates(:other_string, { presence: true })
  validates :features_like, length: { maximum: 255 }
  validates :features_want, length: { maximum: 255 }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/surveys_controller.rb
class SurveysController < ApplicationController

  def home
  end

  def index
  end

  def api
    @surveys = Survey.all
    render :json => @surveys.to_json
  end

  def new
    @survey = Survey.new
  end

  def create
    @survey = Survey.new(survey_params)
    if @survey.save
      flash[:success] = "Thank you! Survey Saved."
      redirect_to surveys_url
    else
      render 'new'
    end
  end

  private
    def survey_params
      params.require(:survey).permit(:name, :age, :gender, :one_note,
        :evernote, :msword, :pages, :google_drive, :excel, :github, :other,
        :other_string, :features_like, :features_want)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/surveys_helper.rb
module SurveysHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:title) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <% flash.each do |message_type, message| %>
      <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
    <% end %>
    <%= yield %>
    <%= debug(params) if Rails.env.development? %>
  </div>
</body>
</html>

app/views/shared/_error_messages.html.erb
<% if @survey.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@survey.errors.count, "error") %>
    </div>
    <ul>
    <% @survey.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/surveys/home.html.erb
<div class="jumbotron">
  <h1>Noted</h1>
  <div class="container">
    <div class="row">
      <div class="col-md-6 col-md-offset-3">
        <a href="<%= new_survey_path %>"><input type="button" class="btn btn-primary" value="Take Survey!"></a>
      </div>
    </div>
  </div>
</div>

app/views/surveys/index.html.erb
<h1>Your opinions will help us make a better note taking app!</h1>

app/views/surveys/new.html.erb
<% provide(:title, "New Survey") %>
<h1>New Survey</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'shared/error_messages', object: @survey %>

    <%= form_for(@survey) do |f| %>

      <%= f.label :name %>
      <%= f.text_field :name, class: "form-control" %>
      <div class="col-md-6">
        <%= f.label :age %>
        <%= f.text_field :age, class: "form-control" %>
      </div>
      <div class="col-md-6">
        <%= f.label :gender %>
        <%= f.text_field :gender, class: "form-control" %>
      </div>
      <div class="col-md-12">
        <div>
          <h2 class="questions">What note taking apps do you currently use?</h2>
        </div>
        <p>
          Select app(s):
        </p>
        <%= f.label :one_note, class: "checkbox inline" do %>
          <%= f.check_box :one_note %>
          <span>One Note</span>
        <% end %>
        <%= f.label :evernote, class: "checkbox inline" do %>
          <%= f.check_box :evernote %>
          <span>Evernote</span>
        <% end %>
        <%= f.label :msword, class: "checkbox inline" do %>
          <%= f.check_box :msword %>
          <span>Microsoft Word</span>
        <% end %>
        <%= f.label :pages, class: "checkbox inline" do %>
          <%= f.check_box :pages %>
          <span>Pages</span>
        <% end %>
        <%= f.label :google_drive, class: "checkbox inline" do %>
          <%= f.check_box :google_drive %>
          <span>Google Drive</span>
        <% end %>
        <%= f.label :excel, class: "checkbox inline" do %>
          <%= f.check_box :excel %>
          <span>Microsoft Excel</span>
        <% end %>
        <%= f.label :github, class: "checkbox inline" do %>
          <%= f.check_box :github %>
          <span>GitHub</span>
        <% end %>
        <%= f.label :other, class: "checkbox inline" do %>
          <%= f.check_box :other %>
          <span>Other</span>
        <% end %>
      </div>
      <%= f.label :other_string, "Other:" %>
      <%= f.text_field :other_string, class: "form-control" %>
      <div>
        <h2 class="questions">What do you like about the apps you currently use?</h2>
      </div>
      <%= f.label :features_like, "Favorite Features:" %>
      <%= f.text_field :features_like, class: "form-control" %>
      <div>
        <h2 class="questions">What additional features would you like to see in a note taking app?</h2>
      </div>
      <%= f.label :features_want, "Requested Features:" %>
      <%= f.text_field :features_want, class: "form-control" %>

      <%= f.submit "Save", class: "btn btn-primary col-md-4" %>
    <% end %>
  </div>
</div>